package com.dailycred.dynamonito.datamodel;

import com.amazonaws.services.dynamodb.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodb.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodb.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodb.datamodeling.DynamoDBTable;

import com.dailycred.dynamonito.core.DynamoDBCache;

/**
 * A model that has an auto generated UUID hash key. We still need to manually set the range key though.
 * 
 */
@DynamoDBCache
@DynamoDBTable(tableName = "DataType")
public class AutoGeneratedKeyModel {

  private String hashKey;
  private String rangeKey;
  private String string;

  public AutoGeneratedKeyModel() {
  }

  @DynamoDBHashKey(attributeName = "hashKey")
  @DynamoDBAutoGeneratedKey
  public String getHashKey() {
    return hashKey;
  }

  public void setHashKey(String hashKey) {
    this.hashKey = hashKey;
  }

  @DynamoDBRangeKey(attributeName = "rangeKey")
  public String getRangeKey() {
    return rangeKey;
  }

  public void setRangeKey(String rangeKey) {
    this.rangeKey = rangeKey;
  }

  public String getString() {
    return string;
  }

  public void setString(String string) {
    this.string = string;
  }

}
